<?php
// automatically load all external libraries (this file is generated by Composer)
require __DIR__ . '/../vendor/autoload.php';

// load our internal libraries too
require_all(__DIR__ . '/model');
require_all(__DIR__ . '/controller');

// http://stackoverflow.com/a/2692367
function require_all($dir) {
    $files = glob($dir . '/*.php');

    foreach ($files as $file) {
        require($file);   
    }
}