<?php
// automatically load all external libraries (this file is generated by Composer)
require __DIR__ . '/../lib/autoload.php';

// manually load all our internal libraries
require_once __DIR__ . '/User.php';
require_once __DIR__ . '/Session.php';