<?php
// automatically load all external libraries (this file is generated by Composer)
require __DIR__ . '/../../vendor/autoload.php';

// manually load all our internal libraries
require_once __DIR__ . '/AccountCommonMethods.php';
require_once __DIR__ . '/AccountDetails.php';
require_once __DIR__ . '/AccountInterface.php';
require_once __DIR__ . '/Database.php';
require_once __DIR__ . '/Dispute.php';
require_once __DIR__ . '/Individual.php';
require_once __DIR__ . '/ModuleController.php';
require_once __DIR__ . '/Notification.php';
require_once __DIR__ . '/Organisation.php';
require_once __DIR__ . '/Register.php';
require_once __DIR__ . '/Session.php';